### ISSUE TITLE
What is the goal of the mongodump for 3.9.12 -> 3.10.2?

### ISSUE THREAD

**Issue by fryfrog** [exsilium/docker-unifi-video#10]
Hey @exsilium, I co-maintain another unifi-video docker image w/ @pducharme and I'm trying to understand the problems w/ 3.9 to 3.10 upgrades. What is the goal in your dump / reload? I *think* it is probably just migrating from `mmapv1` to `wiredTiger` right?

https://github.com/exsilium/docker-unifi-video#upgrade-from-3912-to-3102

I'm trying to figure out an issue where my currently running 3.10.1 instance is *already* wiredTiger engine, but when I *just* upgrade to 3.10.2, it claims the users table is corrupt. Back to 3.10.1 and it works fine again.

**Comment by exsilium** [comment]
Hi @fryfrog , Up to `v3.9.12` the MongoDB version used is `2.6.10`, The `v3.10.x` images are on Bionic Beaver and with the new Unifi controller the MongoDB version is `3.6.3`. The dump / reload was required to ensure proper migration between the engines.

If you are already on 3.10.1, however, I don't see any specific reason why the upgrade path would fail. But just in case check if the MongoDB versions have changed in between.

**Comment by fryfrog** [comment]
Our Docker image has been using MongoDB 3.6 or newer for awhile, mine's actually running 4.0. It's probably worth downgrading. Thanks for confirming what your dump/restore was for.
