### ISSUE TITLE
can't find G3 video camera

### ISSUE THREAD

**Issue by klowy** [exsilium/docker-unifi-video#3]
I followed your terrific guide, but the UNIFI Video page can't locate the camera.

The only step I wasn't able to complete was this (which seems fairly important):

**Camera provisioning**
By default, Docker provides network isolation and due to that the automatic discovery will not work. Directly access your camera IP and enter the host IP of your server where the unifi-video docker image is running.

How do I find the IP address? I did a scan of my network and couldn't find it.

thx

**Comment by exsilium** [comment]
You can try the [Ubiquiti Device Discovery Tool](https://chrome.google.com/webstore/detail/ubiquiti-device-discovery/hmpigflbjeapnknladcfphgkemopofig) chrome extension for that.

By default, cameras get the IP in your network via DHCP, check the most recent IP leases given out (whichever device is the one acting as the DHCP server). You can also try to static-map a MAC ID of the camera for the DHCP to give out a specific IP for the device.

Hopefully this helps. 🍻

**Comment by exsilium** [comment]
Hopefully, your setup works. Closing.
