### ISSUE TITLE
Permission issue possible?

### ISSUE THREAD

**Issue by tinsheets** [exsilium/docker-unifi-video#5]
Dec 17 22:59:55 1a6de92e54ff mongod.27017[1273]: [initandlisten] dbexit: 
Dec 17 22:59:55 1a6de92e54ff mongod.27017[1273]: [initandlisten] shutdown: going to close listening sockets...
Dec 17 22:59:55 1a6de92e54ff mongod.27017[1273]: [initandlisten] shutdown: going to flush diaglog...
Dec 17 22:59:55 1a6de92e54ff mongod.27017[1273]: [initandlisten] shutdown: going to close sockets...
Dec 17 22:59:55 1a6de92e54ff mongod.27017[1273]: [initandlisten] shutdown: waiting for fs preallocator...
Dec 17 22:59:55 1a6de92e54ff mongod.27017[1273]: [initandlisten] shutdown: lock for final commit...
Dec 17 22:59:55 1a6de92e54ff mongod.27017[1273]: [initandlisten] shutdown: final commit...
Dec 17 22:59:55 1a6de92e54ff mongod.27017[1273]: [initandlisten] shutdown: closing all files...
Dec 17 22:59:55 1a6de92e54ff mongod.27017[1273]: [initandlisten] closeAllFiles() finished
Dec 17 22:59:55 1a6de92e54ff mongod.27017[1273]: [initandlisten] shutdown: removing fs lock...
Dec 17 22:59:55 1a6de92e54ff mongod.27017[1273]: [initandlisten] couldn't remove fs lock errno:9 Bad file descriptor
Dec 17 22:59:55 1a6de92e54ff mongod.27017[1273]: [initandlisten] dbexit: really exiting now
cp: cannot create regular file '/usr/lib/unifi-video/data/system.properties': Permission denied
Dec 17 22:59:56 1a6de92e54ff mongod.27017[1316]: [initandlisten] MongoDB starting : pid=1316 port=27017 dbpath=/var/lib/mongodb 64-bit host=1a6de92e54ff
Dec 17 22:59:56 1a6de92e54ff mongod.27017[1316]: [initandlisten] db version v2.6.10
Dec 17 22:59:56 1a6de92e54ff mongod.27017[1316]: [initandlisten] git version: nogitversion
Dec 17 22:59:56 1a6de92e54ff mongod.27017[1316]: [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
Dec 17 22:59:56 1a6de92e54ff mongod.27017[1316]: [initandlisten] build info: Linux lgw01-12 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 BOOST_LIB_VERSION=1_58
Dec 17 22:59:56 1a6de92e54ff mongod.27017[1316]: [initandlisten] allocator: tcmalloc
Dec 17 22:59:56 1a6de92e54ff mongod.27017[1316]: [initandlisten] options: { config: "/etc/mongodb.conf", net: { bindIp: "127.0.0.1" }, storage: { dbPath: "/var/lib/mongodb", journal: { enabled: true } }, systemLog: { destination: "syslog" } }
Dec 17 22:59:56 1a6de92e54ff mongod.27017[1316]: [initandlisten] exception in initAndListen: 10309 Unable to create/open lock file: /var/lib/mongodb/mongod.lock errno:13 Permission denied Is a mongod instance already running?, terminating

I keep getting this - looks like a permission issue, yet I am running it in privilege mode.  Any ideas?

**Comment by exsilium** [comment]
Hi! are you running 3.8.5 or some other version of the image? Not sure about the `cp: cannot create regular file '/usr/lib/unifi-video/data/system.properties': Permission denied` Issue, needs further debugging but concerning the mongod.lock error:

If you've followed the guide, the mongodb directory is located under Host Data Volume directories created during setup (per the guide in: `~/Applications/unifi-video/`). Make sure that the Docker process has the rights to write to that file. If the file exists. shutdown the docker image, delete the file and restart the image.

**Comment by tinsheets** [comment]
I’m running 3.8.5.

Not too sure about the permission issue either, indeed the mongodb is located as directed during set up - but that was my error - I was looking at the file it suggested as the file with the permission issue, not the actual mongodb - I have correct the permission there and that seems to have gotten it - thanks for the help!

**Comment by exsilium** [comment]
Glad you got it working! 👍 Cheers! 🍻 Closing.
