### ISSUE TITLE
Different Recording Path

### ISSUE THREAD

**Issue by Sn0w-blind** [exsilium/docker-unifi-video#6]
Hi,
Firstly, thanks for your work on this, being able to run unified video on my Mac-mini will be perfect. I hadn't even noticed there was no mac version of the video app before i purchased the cameras so finding this was a godsend. :)

II have everything up and running and am now trying to change the recording path to an external drive connected to my Mac-mini.  
When i enter the path in the unifi video configuration it tells me the path does not exist, yet i can cd to the path just fine in terminal. i.e. /Volumes/hdd3/video-data

I have never used docker before, do i need to 'tell' docker about this volume before it can use it?

Thanks in advance
~Matt

**Comment by exsilium** [comment]
Hi!

Docker container should be treated as a disposable and stateless container, it ensures that it's easy to upgrade to newer versions. So all the persistant data that unifi video needs, is part of the Host Data Volumes that you mount when you first time instantiate the container. You are correct that docker container does not know anything about the `/Volumes/hdd3/video-data`.

If you used the guide and take a look of the `run.sh` It defines the root of the host data volume in the form of the `BASEDIR` variable.

https://github.com/exsilium/docker-unifi-video/blob/f6a410a6c487d3d8f7dcd820afa7ea6fcc0bb697/run.sh#L3

In your case I'd suggest that you just use your external hard drive as the basedir so changing that to `/Volumes/hdd3/unifi-video` would ensure that all the persistent data that unifi-video requires (including the recordings) are stored there.

Welcome to the world of Docker, you've been missed! 🎉 🎈 

I hope this helps.

Cheers! 🍻

**Comment by Sn0w-blind** [comment]
I was just re-looking at exactly that actually and wondering if i could separate out the data path.  Just changing the base dir makes sense.
Thanks for the speedy reply!
Cheers.
